### ISSUE TITLE
Can't Launch v0.7.0-beta1

### ISSUE THREAD

**Issue by zepgurl** [snark/jumpcut#13]
Downloaded v0.7.0-beta1, deleted old version, installed the beta and the system says it can't be opened because Apple cannot check it for malicious software. Mojave 10.14.6
<img width="532" alt="Screen Shot 2019-08-20 at 9 43 47 PM" src="https://user-images.githubusercontent.com/47155500/63399235-7dd27a00-c395-11e9-9d07-c645e01fc3bf.png">

**Comment by snark** [comment]
Are you running out of the Applications folder? If so, can you try this in Terminal:

codesign -dv --verbose=4 /Applications/Jumpcut.app/

And paste the results?

**Comment by snark** [comment]
The output of this will also be helpful:

spctl --assess -vvv /Applications/Jumpcut.app

**Comment by snark** [comment]
Okay, some additional checking suggests that this is because the beta isn't notarized by Apple. @zepgurl If you right-click it, I believe you'll be able to open it. (Even this workaround apparently isn't available on Catalina without dinking around with one's Gatekeeper profile, so I'll notarize subsequent betas.)

**Comment by snark** [comment]
@zepgurl A new beta has been released, that hopefully got hardening and notarizing working correctly.

**Comment by seren** [comment]
FYI, the new beta2 launches for me on Mojave 10.14.6.

**Comment by zepgurl** [comment]
I concur, beta2 launches.
