### ISSUE TITLE
Update to new version fails.

### ISSUE THREAD

**Issue by genintho** [snark/jumpcut#25]
Long time user, and very grateful for jumpcut!
Thank you for the updates to keep this amazing software working with new version of MacOs. But please keep jump cut simple. 

Unfortunetly, I can not install the new version!

I am on 0.63

<img width="434" alt="Screen Shot 2019-09-22 at 8 13 04 PM" src="https://user-images.githubusercontent.com/664857/65400191-b343fc00-dd75-11e9-9c1c-1451c56c69d1.png">

I could not see any thing obvious around what is going in the Console app logs but I can provide them if that's helpful.

**Comment by snark** [comment]
@genintho This is a known issue with upgrading via Sparkle from 0.63. I believe the problem is that the signing method used for Sparkle in 2019 isn't known by the (ten year old) version of Sparkle in 0.63. I do want to figure out what's going on, but I'm not sure it's going to be easy or even possible to fix. Your best bet is downloading a fresh copy of 0.71 from Github, or using Homebrew to install.

**Comment by genintho** [comment]
homebrew it is then.

thank you for the answer
