### ISSUE TITLE
Jumpcut 64bit for Catalina

### ISSUE THREAD

**Issue by jaymus** [snark/jumpcut#32]
Out of all the apps, I probably use Jumpcut the most. It's such an important part of my workflow. But it looks like it won't work if I upgrade to Catalina. Any plans on updating, or any workarounds?

**Comment by snark** [comment]
@jaymus You should be able to use the 0.7x branch on Catalina; please give it a whirl and let me know if you have any trouble. You can download it using Homebrew Cask, or directly from the website: https://snark.github.io/jumpcut/

**Comment by jonmunson** [comment]
I have just reinstalled using Homebrew Cask after update to Catalina, and also not working. Running version 0.71.

**Comment by snark** [comment]
Crap. Thanks, @jonmunson -- if you fall back to version 0.70, does it work? Can you describe the failure mode? I'm on 0.71 but not on Catalina, and it (correctly, as far as I can tell!) identifies both Jumpcut and the internal JumpcutHelper used for autolaunching as coming from an identified developer (me) and being 64-bit, so I'm not sure why it would fail.

**Comment by snark** [comment]
@jonmunson @jaymus I just got access to a computer running Catalina, 10.15.1. On a fresh install, Jumpcut 0.71 is working as expected: I installed via Homebrew cask and Jumpcut launched and asked for permission to control my computer; when that was granted (and I set a hotkey), Jumpcut responds to the hotkey and pastes as anticipated. Can you describe how it fails for you?

If you two upgraded from Mojave, my suspicion is that this is in some sense the same problem as issue #17. Can you confirm that Jumpcut is listed and checked in the Security & Privacy preference panel, under "Privacy > Accessibility"? If that is the case, can you try manually removing Jumpcut (using the "-" button) and then re-adding it?

**Comment by jaymus** [comment]
I'm currently on Mojave. I plan on upgrading to Catalina this weekend so I have some time to troubleshoot if things go awry before another work week begins. I'll make sure I document what I see and report back.

**Comment by jaymus** [comment]
![image](https://user-images.githubusercontent.com/28311778/68357076-3335e380-00e2-11ea-9747-a88a25eef7de.png)

**Comment by jaymus** [comment]
FYI, the original reason for this thread was the screenshot above. Since Catalina will no longer support legacy software, I was assuming jumpcut wouldn't work. It's version 0.71 but still reads as 32 bit.

**Comment by snark** [comment]
@jaymus Okay, that's _super_ weird. In the System Profile, can you also look under Applications (not Legacy Software) to see if Jumpcut is also listed there? On my main machine, I see Jumpcut listed both under Legacy Software (for dev versions[1]) and Applications; on the Catalina box, it's showing up under Applications as expected.

But based on my experience with this new laptop, you should be good to go -- although it's possible upgrading rather than starting from scratch is going to lead to problems, which will be useful to know separately.

(And thanks for taking the time to file the report! I'm not really a Mac developer, so maybe this is a normal thing that people are awarer of, but I'm currently very confused as to what the System Profile is reflecting.)

[1] e.g. in `~/Library/Developer/Xcode/Archives/2019-08-30/Jumpcut 8-30-19, 10.26 PM.xcarchive/blah blah blah`

**Comment by jaymus** [comment]
Yes, very strange. In the applications, it's listed as 64 bit.

![image](https://user-images.githubusercontent.com/28311778/68449528-77de7f00-01b5-11ea-9279-e00d1865fdcb.png)

**Comment by snark** [comment]
@jaymus How did the upgrade go?

**Comment by jaymus** [comment]
It's running right now! We'll see this evening after I'm off work.

**Comment by jaymus** [comment]
Happy to report that jumpcut works perfectly after the upgrade. I've used it across several apps and it seems to be functioning normally.

**Comment by snark** [comment]
Thanks, @jaymus! That corresponds to my experiences. I'm going to close this and open a low-priority one to see if I can figure out why it reports as 32-bit.

**Comment by mijogu** [comment]
@jaymus what was it that worked for you? did you have to uninstall/reinstall Jumpcut? downgrade? upgrade? 

I absolutely love Jumpcut, recently started using keyboard shortcuts and it's killer.
