### ISSUE TITLE
Paste or copy an entry depending on which click is used

### ISSUE THREAD

**Issue by nclm** [snark/jumpcut#33]
Half of the time when I click on an entry in my Jumpcut menu, I just want it to be copied to the clipboard for future pastes. Other other half of the time, I’d like it to be pasted directly in the currently selected field. I know there is a global option to choose this behaviour, but the idea here is that it really depends on the times.

Here is a way to solve it: left-clicking an entry would do the main action (for instance, getting it in the clipboard) and middle-clicking (or right-clicking, a little less natural) would do the secondary action.

It's would be an invisible feature, probably mentioned in the preference windows, useful to those who need it but not getting in the way of anyone else :)

**Comment by snark** [comment]
@nclm This is a feasible feature request. I've been noodling with using right-click for activating an extended menu, however, so let's tease out some UX thoughts. (I myself am almost always on a laptop and use the keyboard interface much more than the menu bar 

1. You'd want this to be menu-driven, not keyboard driven? (That is, you wouldn't want to use space or some similar character in the bezel to add to the clipboard but not paste?)
2. You'd want it to be mouse-driven, rather than (e.g.) a menu-based toggle, or a hotkey to toggle back and forth?
3. And you'd want it to be based on right- (or center-)clicking the menu item, rather than how you click the menu status item itself? (I don't know if that's possible to do or how easy it is, but it's certainly a legitimate *request*.)

**Comment by snark** [comment]
@nclm It's been more than a year -- I just wanted you to know that this is still on my radar but will probably not happen until an extensive rewrite (in Swift) which I hope to have out by the end of 2021.

**Comment by snark** [comment]
@nclm Well, I didn't get it done by the end of 2021, but this feature is on my radar for the current rewrite in Swift. I'll make sure to notify you when it's released and I close the ticket!

**Comment by snark** [comment]
The prophecy is fulfilled! This is now available in the newly-released Jumpcut 0.80.

**Comment by nclm** [comment]
Thanks!
