### ISSUE TITLE
Jumpcut doesn't start after reboot even with "Launch Jumpcut on login" checked

### ISSUE THREAD

**Issue by fjanon** [snark/jumpcut#42]
Jumpcut doesn't start after reboot even with "Launch Jumpcut on login" checked.

I have to launch Jumpcut manually each time I reboot MacOS.

System Version:	macOS 10.14.6 (18G95)
Kernel Version:	Darwin 18.7.0

**Comment by snark** [comment]
@fjanon Thanks for the report -- what version of Jumpcut are you using?

**Comment by fjanon** [comment]
I use 0.72

**Comment by snark** [comment]
@fjanon That's curious--my wife is on 10.14 and I know launch at login is working for her. Is Jumpcut installed in /Applications? If it isn't, I know that can interfere with the launch behavior.

If it is, do you see any mention of Jumpcut or JumpcutHelper in Console after reboot?

**Comment by thelonious89** [comment]
I too have been having this issue for about a year. I solve dit about 6 months ago after reading a top inline, but now that I have a new laptop I'm trying to find that tip on fixing this behaviour and I'm unable to spot it. Any idea on how to fix this? It's annoying to restart and then do lots of copying and then go to paste and find all my copies are not in jumpcut because it's not opened ;-)

**Comment by snark** [comment]
@thelonious89 Sorry, I missed your comment! There's a new release coming shortly (universal build for Intel/Apple Silicon Macs), so I'll take a couple minutes to look at it. (@fjanon, same applies to you.)

**Comment by snark** [comment]
@thelonious89 @fjanon This is still a live issue for you, correct? If you're using 0.75 (and Jumpcut is installed in /Applications), can you try going to Preferences/General, disabling "Launch on Login", quitting, restarting Jumpcut, and re-enabling the preference? I 100% believe you that this is happening but haven't been able to replicate.
