### ISSUE TITLE
Pasting in wrong window when app open on multiple screens

### ISSUE THREAD

**Issue by atopiler** [snark/jumpcut#54]
I have an external monitor, and when I have an application open on both screens (e.g. Chrome), and I try to use Jumpcut to paste in my active window (on external monitor, which I use as my primary window), it always switches focus to the window on my other screen on the laptop itself and pastes there.  This has been totally infuriating since it makes jumpcut unusable with my setup.  

I'm on a 2018 Macbook Pro with OSX 11.1 Big Sur.  I noticed that this only recently began happening after a recent upgrade (not sure whether it was when original upgrading to Big Sur 11.0, or the latest 11.1 update).  

To replicate:
* Have external monitor set as the primary display, and laptop screen as the secondary display
* Have a window of the same application open on both displays
* While working actively in the window that's on the primary display (on external monitor), try using jumpcut -- this will automatically activate/focus on the inactive app window on the laptop display and paste the snippet only in that window.  
    * It is impossible to paste your snippet on the active window on an external display unless it is the only open window.
    * Minimizing all other windows on the laptop display allows for pasting on the active window in the external monitor, but this is obviously not a viable solution since that defeats the purpose of having multiple displays.

**Comment by snark** [comment]
Thanks for the bug report; I don't have access to an external monitor at the moment to try to replicate and figure out what's going on, but I'll see if I can get this sorted out.

**Comment by gabrielboucher** [comment]
I have the same issue and something I noticed that could be of help is that Jumpcut widget always appears on the "main" screen, e.g. the one that has the menu bar on it (see screenshot), regardless of the cursor being on that screen or not. It then  paste to the application window on that (main) screen, even if it's not the active application window.

I assume the desired behaviour would be to show the widget on the active screen e.g the one that has the mouse cursor on it and of course, paste the content on the application window that is on the active screen.

![Screen Shot 2021-04-14 at 3 14 33 PM](https://user-images.githubusercontent.com/2014376/114766470-6eefc680-9d34-11eb-8dda-0dea1d6e6a27.png)

Since one of the most useful use case for jumpcut is to remove the formatting, I use it all the time but can't use it on a dual monitor setup to paste from one browser window to the other.

**Comment by snark** [comment]
@gabrielboucher @atopiler I have no particular reason to think that this was fixed by the Swift rewrite, but please let me know if this is still an issue for you in 0.80; as soon as I get access to a second screen, I'll see what I can do to replicate the problem.

**Comment by drb80** [comment]
I'm not sure about the multiple monitor problem in the rewrite, but that rewrite did change the behavior when attempting to paste in a full-screen window. In the previous version, it would stay on the same desktop and now it switches to the one with the menu bar. This might be related to the multiple monitor issue. Regardless, great app and I find it indispensable!

**Comment by itzawrap** [comment]
Love Jumpcut. The simplest most unobtrusive paste board clipping history app. Very nice. Been using it for years. Saves my butt all the time because the simple Mac clipboard is very limited. Newest version .80 however does not work on my main screen, while works fine on my secondary screen. Catalina 10.15.7 MBP 16 2019 32gb ram, 2tb ssd drive. Any ideas why this is happening? Previous version .71 was fine and worked on both screens equally well.

**Comment by snark** [comment]
@itzawrap The application was entirely rewritten for a variety of reasons, which will be great going forward but means I introduced a number of bugs in less heavily exercised portions of the code. I've never used a dual-monitor setup, so this is one of them!

@gabrielboucher @atopiler FWIW one of the reasons I rewrote it in Swift is to get better access to canned solutions for this sort of relatively common problem; I've got a potential solution that I'll be trying (not in the next release, which will be sometime this week, but hopefully the one after that).

**Comment by snark** [comment]
@itzawrap @gabrielboucher @atopiler I have an experimental build that hopefully is going to fix this problem, but I can't test since I don't have a dual-monitor setup. Shoot me an email at the contact listed in my GitHub profile if you want to try it out!

**Comment by drb80** [comment]
0.81 fixed the issue I was having, thanks so much for everything! Love jumpcut.

**Comment by snark** [comment]
0.82 has been released with an additional set of improvements for dual-monitor use. @itzawrap @gabrielboucher @atopiler Please let me know if this solves the problems you were having!

**Comment by snark** [comment]
I'll leave this ticket open for a while in case I'm wrong but unless @atopiler or @itzawrap report ongoing issues it sounds like this is fixed.

**Comment by snark** [comment]
All right, going to assume that this is now working for folks. Feel free to report in this issue or start a new one if I'm wrong!

**Comment by berdon** [comment]
@snark 
I was wondering if we might reopen this issue - here's what I'm seeing which I believe is this same issue:

**Setup:**
- Have multiple monitors (M1 and M2)
- Have multiple windows of one application open (W1 and W2)
  - For example, VSCode
- Configure jumpcut to _not_ paste on hotkey/history cycling (untoggle `menu selection`)
  - Note: I don't think this is required; in fact, if you leave this checked, it will present an equally bad behavior

**Repro Steps:**
- Leave one window (W1) visible on one monitor (M1), minimize the other window (W2)
- In the open window (W1), use hotkeys to cycle backward and forward in the clip history
- Release the hotkeys
- The minimized window on the other monitor (W2 on M2) immediately unminimizes and steals keyboard focus

Note: If `menu selection` selection is left on, when the hotkey is released and W2 becomes visible, the text is pasted in the wrong window.
