### ISSUE TITLE
Bezel working intermittently in Monterey 12.0.1

### ISSUE THREAD

**Issue by SusumuKusa** [snark/jumpcut#63]
Selecting/pasting from menu bar works fine 100% of the time, but using keyboard shortcut the bezel displays only intermittently. Curiously, applying a 'paste item' via the menu bar then gets the bezel working again, for a while.

(Monterey 12.0.1, build 21A559)

**Comment by snark** [comment]
@SusumuKusa Thanks -- anything else you're running that would might be conflicting with the hotkey you're using? Can you describe what you mean by "intermittently" (i.e. does it appear only sometimes when you hit the hotkey, reliably appear but then disappear while you're choosing a clipping, or some other behavior)?

Currently I don't have access to a machine running Monterey, just Big Sur, but I will investigate as soon as I have access to the new OS.

**Comment by DefV** [comment]
I seem to be having the same issue. I think I can specify the issue a bit more, for me it seems to be related to terminal.

When I try to use the keyboard shortcut to open up the Jumpcut window in apps like Safari or Mail, it works fine. When I use the shortcut in Terminal, it doesn't show up, and it stops working until I use Cmd+Space to open Jumpcut (which then show the bezel)

I've seen other strange behaviours in Terminal, not related to Jumpcut, happen in Monterey. eg editor windows appearing below Terminal, not getting focus, etc.

Let me know if there's anything I can do to debug this further.

**Comment by SusumuKusa** [comment]
@snark I've realised that, for me, the issue seems somehow related to fields on websites used to enter usernames, passwords and whatever else (I can replicate the issue on both Safari and Firefox, but Chrome I try to keep off my Mac!).

Basically, the hotkey works fine until I attempt to use it to drop a text clipping into one of these fields. The hotkey combo will fail to drop anything into the field, and the hotkey option will then stop working across my entire system, until I instead use the menu bar drop-down to paste a single clipping somewhere, into say a text file or wherever. The hotkey combo will then start working again, until I next try to paste a clipping into a website field.

Hope that all makes sense. I can send a screen capture video if that helps. My Safari version is 15.1; build 17612.2.9.1.20.

**Comment by snark** [comment]
@DefV @SusumuKusa Thanks for the additional details; I suspect I'm not going to be able to reproduce this until I upgrade to Monterey on my laptop. For both of you, are there any similar issues when just using Apple-V to paste? (Neither of you is on a keyboard other than US/QWERTY, correct?)

**Comment by SusumuKusa** [comment]
@snark Hi, I'm on a Japanese-JIS keyboard, but there roman characters still appear in the QWERTY layout. Input languages are set to 'ABC' and 'Japanese'. No similar issues when simply using Apple-v to paste, no.

I can't say whether this is exclusively a Monterey thing, as I skipped Big Sur completely, moving from Catalina to Monterey. All was fine under Catalina.

**Comment by disbelief** [comment]
I'm having a similar issue, but more severe. In addition to not always pasting, the Jumpcut icon only sometimes appears in the menu bar, even while it is running (process is visible in Activity Monitor). Furthermore, I have to restart jumpcut frequently as it simply "disappears" and the hotkey doesn't trigger it.

I'm on a new M1 Max MacBook Pro running macOS 12.0.1 Monterey. I wonder if the camera notch is interfering with jumpcut in some way?

**Comment by snark** [comment]
Thanks, @disbelief (and @SusumuKusa and @DefV) -- I'm on Big Sur on my more modern machine (M1 Air), so I can't replicate immediately, but when I upgrade I will dig in.

@disbelief Have you observed any issues with other menu items disappearing due to the notch? If you move it further to the right so it doesn't ever intersect the notch, are you having similar issues? Are you using Dozer/Bartender/HiddenBar or anything? I'm using absolutely no nonstandard APIs for the menu bar icon, so it's somewhat perplexing that you're having issues.

**Comment by disbelief** [comment]
@snark I haven't noticed any similar behavior from other menu items, though there is one that always appears behind the notch and I can still click it. I don't use any other menubar management utilities like the ones you've mentioned. The only thing I can think of is Karabiner Elements for keyboard mapping but I've used that with Jumpcut for years on previous machines.

I'm actually in the failure state at the moment. I can see `jumpcut` process in Activity Monitor, but hotkey not working and no menubar icon:
<img width="1002" alt="Screen Shot 2022-01-03 at 15 09 40" src="https://user-images.githubusercontent.com/295574/147947001-2d238fc9-6232-4708-ba6e-054b9822a3f6.png">

Is there anything I can do to help diagnose? I don't see any mention of jumpcut in system.log

**Comment by snark** [comment]
That's weird and fascinating! `ps -ax | grep Jumpcut` shows it as well? (I'd presume so if it's in the Activity Monitor.) It's not in the gap of the two icons in the left, is it, hidden due to some sort of weird interaction with dark mode on Monterey?

**Comment by disbelief** [comment]
Yep it appears in `ps` in the terminal as well.

That weird gap is an artifact of taking a screenshot with the notch I think. The gap is where the notch starts. Clicking in that space doesn't do anything.

**Comment by snark** [comment]
@disbelief I'm not sure how willing you'd be to run a build with some extra logging thrown in, but if you'd be up for it, ping me at the email address given in my profile. I don't know whether it'd be worth digging into this before I upgrade to Monterey  or how much time I'll have available in the next few weeks, but this is very curious.

**Comment by bwhaley** [comment]
Not sure whether my comment belongs here or in #54... I'm on an M1 Max and I'm finding that when I have an external display connected with the MBP lid open, the Jumpcut bezel (when using the keyboard shortcut) is on the wrong screen. It's showing up on the MBP screen rather than the external display which is where the active window is. Also, sometimes the bezel is showing up halfway off the screen and only partly visible.

**Comment by jnubz** [comment]
This comment thread got messy. Is this issue about menu bar notch or the keyboard shortcut not showing the clipboard memory bezel?

I wanted to chime in and concur that the keyboard shortcut doesn't work in macOS 12.x if you are in a secure field such as inputting secure credentials. I suspect it has to do with the secure expansion that text expander also struggles with, but I know it's possible to circumvent.

**Comment by sometimesfood** [comment]
> This comment thread got messy. Is this issue about menu bar notch or the keyboard shortcut not showing the clipboard memory bezel?

The bezel does not reliably come up when pressing the keyboard shortcut. (See below for details.)

> I wanted to chime in and concur that the keyboard shortcut doesn't work in macOS 12.x if you are in a secure field such as inputting secure credentials. I suspect it has to do with the secure expansion that text expander also struggles with, but I know it's possible to circumvent.

Yes, that seems to be what triggers the bug. If I try to bring up the bezel using the keyboard shortcut while my cursor is in a secure field, the bezel does not come up.

The main problem for me is that the bezel cannot be brought up via the keyboard shortcut afterwards. The bezel stays hidden, even if I move the cursor to a completely different window and use the keyboard shortcut again.

The bezel does not reappear until I click Jumpcut's menu bar icon and "Preferences" or "About Jumpcut".

Once I have clicked those, everything works fine until I try to bring up the bezel again when the cursor is in a secure field.

**Comment by xavier-contreras** [comment]
I'm having the exact issue as [DefV](https://github.com/DefV) from [on Nov 10, 2021](https://github.com/snark/jumpcut/issues/63#issuecomment-965294332).  100% reproducible on terminal, where I need jumpcut the most unfortunately.  I'm on OSX 12.3

Works fine in chrome, but as soon as I try to use it on a terminal window it breaks and I have to go work around it.

**Comment by Vadorequest** [comment]
I recorded a video of what happens on my computer.
The Bezel doesn't show when I target a "Password" input on Brave browser.

### 🍿https://watch.screencastify.com/v/b6vN82WZUeGD9KgKh24Q

**Comment by snark** [comment]
Okay, breaking down the various issues:

1) The issue originally reported by @DefV: There's a Terminal option which prevents monitoring keystrokes; this can interfere with global hotkey detection in Monterey. (FWIW it does not occur, as far as I can tell, in Big Sur, which is what I use on my day-to-day computer, but I've replicated the issue in Monterey.) Thanks to @xavier-contreras for spelling this one out; as far as I can tell, this is an instance of things working as designed. Workarounds would include using the status bar menu while in Terminal or disabling Secure Keyboard Entry. For what it's worth, in Jumpcut 0.81, the failed display of the bezel at least doesn't seem to prevent the bezel from displaying elsewhere, but see note 5 below.
2) The Jumpcut status bar icon can get hidden under the notch. Not a ton to be done about this, I don't think, although I could potentially issue some sort of alert in that scenario. (@disbelief Are you still having this issue in 0.80/0.81?) This seems unrelated to the other problems discussed in this issue.
3) Secure fields in browsers are exhibiting similar problems in Monterey. (I've validated this on Safari and Chrome, under 0.81, using Gmail's login field.) Notably, checking "show password" fixes the issue. As in note one, under 0.81, it doesn't seem to have lingering effects on the bezel, at least for me; if I switch back to a text editor after failing to bring up the bezel, I can do so again normally. (See note 5.) This is once again, I think, things working as designed; Monterey blocks global event listeners when the secure field is in focus to prevent keylogging, so the hotkey library in use (soffes/HotKey) never receives the event to bring the bezel up. Using the status bar icon works in this instance. 
4) Pasting into some secure (OS) fields in Monterey doesn't work. Bringing up the bezel in some secure context also doesn't work. (I've replicated this in Monterey using Keychain Access; the popup for unlocking the Security & Privacy preferences works differently and doesn't seem to have this problem.) I can't even use the menu item in this instance, possibly due to how the modal works.
5) There's a known issue--plausibly carried over from the Objective-C version of Jumpcut--where multiple monitors throw off Jumpcut's display behavior. 0.80 additionally had a problem with multiple desktops under Mission Control that was rectified in 0.81. This could lead to some of the behavior where Jumpcut doesn't display the bezel correctly, if you're in in a dual-monitor situation or previously if you were using multiple spaces. This one is a top priority for me to fix, although we don't know if that will lead to better behavior for any of the problems reported in this issue. This is maybe the original issue that @SusumuKusa experienced?

I've got some notes towards better documentation, so I'll make sure to add the issues with Terminal and secure fields as a FAQ when that goes up. I'd also be *thrilled* if people can confirm that, under 0.81, failing to activate the bezel in a secure browser field in Monterey doesn't cause bezel lockup. As the developers of TextExpander note, there are occasionally buggy implementations of secure field behavior that don't turn off correctly, but hopefully normal situations like "I wanted to paste into a password field in Safari" are not among them.

**Comment by disbelief** [comment]
Regarding the icon being hidden behind the notch, that hasn't happened to me in a while. I've also upgraded to the new Swift rewrite version recently and so am getting used to the new look and feel and slightly different behaviour. So far no problems aside from the Space focus issue which you've already fixed.

**Comment by snark** [comment]
@disbelief FWIW, I've partially addressed the notch issue in 0.82 by setting the Preference window to always display when the icon is double-clicked while the application is running. I believe issue #5 has been fixed.

**Comment by disbelief** [comment]
It's been working like a charm for me since the upgrade. No issues to report!
