### ISSUE TITLE
No more?

### ISSUE THREAD

**Issue by mkay581** [snark/jumpcut#8]
Hey, I love this script. I mean really LOVE this script. And I'm sure I'm not the only one. Are there any plans to update this or actively maintain it in the future?

**Comment by snark** [comment]
Mark, thanks -- there's at least one more release I should put out, as
there's a security vulnerability in the Sparkle auto-update library Jumpcut
uses as it's currently implemented (which is the fault of my
implementation, not Sparkle itself), and a few things I should fix while
I'm dusting off the code base. I'm a lot older and busier than when I first
started Jumpcut, so I've been putting it off for months (even ignoring the
years since the last release) but it's not entirely dead yet.

**Comment by snark** [comment]
@mkay581 FWIW, a new version has been released (10 years after the last one!)
