### ISSUE TITLE
Can not use bezel while focus is on password input field macOS 12.2+

### ISSUE THREAD

**Issue by Hursofid** [snark/jumpcut#85]
Hi, I'm using Jumpcut since I got my first mac and after macOS update 12.2+ I've noticed that I'm unable to open bezel menu with hotkey when focus is on password input field. It works fine anywhere else but the password fields.
I'm pretty sure it was working on 12.1 and earlier.
It does not matter where the password input field is (default Terminal app, Electron-based app like Discord, websites in Safari, pop-ups with HTTP Basic Authentication).
I can't think about any other detail I may forgot to mention, but I remain at your disposal to help and find where the issue is.

macOS Monterey 12.6, Jumpcut latest 0.82

**Comment by sercanersoy** [comment]
Same issue here ➕

**Comment by sercanersoy** [comment]
My environment is macOS Monterey 12.5, Jumpcut 0.82

**Comment by snark** [comment]
@Hursofid @sercanersoy As far as I've been able to determine, this is because in Monterey and later, macOS prevents global keyDown events from propagating while entering text into the password field. Presumably this is to block keyloggers; it will still work pasting manually (or using the menu bar to paste, since that doesn't rely on listening for a keyboard event).

See, e.g., <https://wiki.keyboardmaestro.com/Troubleshooting>:

```
However, in a password field (or any time Secure Input is enabled), Keyboard Maestro and other applications cannot see the state of the keyboard (for obvious security reasons). Because of this, Keyboard Maestro does not know that you are still holding down a key and therefore cannot know to release it.
```

Jumpcut doesn't simulate typing the string, but the issue is the same: inside a password field, the events get blocked. I'm fairly sure this is something that I won't be able to work around at the application level but I should add it to the FAQ.

**Comment by Hursofid** [comment]
Thanks for clarifying, I'll close the issue on your behalf.
